### ISSUE TITLE
Compatibility Request - Refined Storage Importers/Extra Storage Advanced Importers

### ISSUE THREAD

**Issue by AerosAtar** [Corgam/CagedMobs#45]
Currently cages and hopping cages do not work if connected directly to Importers - items are not pulled out of regular cages, and hopping cages cannot push items either. It would be great if this could be addressed, though I am unsure how realistic the request is.

**Comment by Corgam** [comment]
It would not be so easy to implement this request. The cages themselves do not have any item slots (inventory), thus the importers for some networks do not have a place to import from. When it comes to the exporters, it depends on the type of the exporter (and if it has the inventory itself). For example, I can image that putting the cage on top of the AE Interface would work because the Interface has inventory itself and the cages are pushing their content to the inventory below.

So as you can see, unfortunately, I will not do anything to fulfill this request, because the functionality depends on the importer/exporter of the item network mods.
